config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :posts, only: [:index, :show]

  # stripe listen --forward-to localhost:3000/stripe/webhooks
  post 'stripe/webhooks', to: 'stripe/webhooks#create'
  get 'pricing', to: 'stripe/checkout#pricing'
  post 'stripe/checkout', to: 'stripe/checkout#checkout'
  get 'stripe/checkout/new', to: 'stripe/checkout#new'
  get 'stripe/checkout/success', to: 'stripe/checkout#success'
  get 'stripe/checkout/cancel', to: 'stripe/checkout#cancel'
  post 'stripe/billing_portal', to: 'stripe/billing_portal#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create do
    stripe_customer = Stripe::Customer.create(email: email)
    # stripe_customer_id = stripe_customer.id
    # update(stripe_customer_id: stripe_customer_id)
  end

  def active?
    return true if plan == 'lifetime'
    return false unless subscription_ends_at.present?

    subscription_ends_at > Time.zone.now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = if current_user&.active?
              Post.all
              else
                Post.where(premium: false)
              end
  end

  def show
    @post = Post.find(params[:id])
    if @post.premium? && !current_user.active?
      redirect_to posts_path, alert: "Post for premium subscribers"
    end
  end
end

app/controllers/stripe/billing_portal_controller.rb
class Stripe::BillingPortalController < ApplicationController
  def create
    session = Stripe::BillingPortal::Session.create({
                                                      customer: current_user.stripe_customer_id,
                                                      return_url: pricing_url
                                                    })
    redirect_to session.url, allow_other_host: true
  end
end

app/controllers/stripe/checkout_controller.rb
class Stripe::CheckoutController < ApplicationController
  def pricing
    lookup_keys = %w[monthly yearly lifetime]
    @prices = Stripe::Price.list(lookup_keys: lookup_keys, active: true, expand: ['data.product']).data.sort_by(&:unit_amount)
  end

  def new
    price = Stripe::Price.retrieve(params[:price_id])
    @session = Stripe::Checkout::Session.create({
      customer: current_user.stripe_customer_id,
      mode: mode(price),
      line_items: [{
        quantity: 1,
        price: params[:price_id]
      }],
      return_url: pricing_url,
      ui_mode: 'embedded'
      })
  end

  def checkout
    price = Stripe::Price.retrieve(params[:price_id])
    session = Stripe::Checkout::Session.create({
      customer: current_user.stripe_customer_id,
      mode: mode(price),
      line_items: [{
        quantity: 1,
        price: params[:price_id]
      }],
      success_url: stripe_checkout_success_url,
      cancel_url: stripe_checkout_cancel_url,
      })
    redirect_to session.url, allow_other_host: true
  end

  def success
    flash[:notice] = "success"
    redirect_to pricing_path
  end
  
  def cancel
    flash[:alert] = "failure"
    redirect_to pricing_path
  end

  private

  MODES = {
    'recurring' => 'subscription',
    'one_time' => 'payment'
  }.freeze

  def mode(price)
    MODES[price.type]
  end
end

app/controllers/stripe/webhooks_controller.rb
class Stripe::WebhooksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    # Replace this endpoint secret with your endpoint's unique secret
    # If you are testing with the CLI, find the secret by running 'stripe listen'
    # If you are using an endpoint defined with the API or dashboard, look in your webhook settings
    # at https://dashboard.stripe.com/webhooks
    webhook_secret = 'whsec_your_webhook_secret_here'
    payload = request.body.read
    if !webhook_secret.empty?
      # Retrieve the event by verifying the signature using the raw body and secret if webhook signing is configured.
      sig_header = request.env['HTTP_STRIPE_SIGNATURE']
      event = nil
    
      begin
        event = Stripe::Webhook.construct_event(
          payload, sig_header, webhook_secret
        )
      rescue JSON::ParserError => e
        # Invalid payload
        status 400
        return
      rescue Stripe::SignatureVerificationError => e
        # Invalid signature
        puts '⚠️  Webhook signature verification failed.'
        status 400
        return
      end
    else
      data = JSON.parse(payload, symbolize_names: true)
      event = Stripe::Event.construct_from(data)
    end
    # Get the type of webhook event sent - used to check the status of PaymentIntents.
    event_type = event['type']
    data = event['data']
    data_object = data['object']
    
    case event.type
    when 'customer.created'
      customer = event.data.object
      user = User.find_by(email: customer.email)
      user.update(stripe_customer_id: customer.id)
    when event.type == 'customer.subscription.deleted', 'customer.subscription.updated', 'customer.subscription.created'
      subscription = event.data.object
      user = User.find_by(stripe_customer_id: subscription.customer)
      user.update(
        plan: subscription.items.data[0].price.recurring.interval,
        subscription_status: subscription.status,
        subscription_ends_at: Time.at(subscription.current_period_end).to_datetime
      )
    when 'checkout.session.completed'
      session = event.data.object
      # handle one time payment
      if session.mode == 'payment' && session.payment_status == 'paid'
        user = User.find_by(stripe_customer_id: session.customer)
        session_with_line_items = Stripe::Checkout::Session.retrieve({ id: session.id, expand: ['line_items'] })
        plan = session_with_line_items.line_items.data.first.price.lookup_key # "lifetime"
        user.update(plan:)
      end
    end
    
    render json: { message: 'success' }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails7StripeSaas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p style="color: green"><%= notice %></p>
    <p style="color: red"><%= alert %></p>
    <%= link_to 'Posts', posts_path %>
    <% if signed_in? %>
      <hr>
      <%= link_to current_user.email, edit_user_registration_path %>
      <%= current_user.stripe_customer_id %>
      <%= current_user.plan %>
      <%= current_user.subscription_status %>
      <%= current_user.subscription_ends_at %>
      <%= current_user.active? %>
      <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: "false" } %>
      <hr>
      <%= link_to 'Pricing', pricing_path %>
      <%= button_to 'Billing portal', stripe_billing_portal_path, data: { turbo: "false" } %>
    <% else %>
      <hr>
      <%= link_to "Log in", new_user_session_path %>
      <%= link_to "Register", new_user_registration_path %>
    <% end %>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Premium:</strong>
    <%= post.premium %>
  </p>

</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/stripe/checkout/new.html.erb
<%= javascript_include_tag "https://js.stripe.com/v3/" %>

<%= tag.div data: {
  controller: "stripe--embedded-checkout",
  stripe__embedded_checkout_public_key_value: 'pk_test_your_stripe_public_key',
  stripe__embedded_checkout_client_secret_value: @session.client_secret
} %>

app/views/stripe/checkout/pricing.html.erb
<% @prices.each do |price| %>
  <div>
    <%= price.product.name %>
    <%= price.currency %>
    <%= price.unit_amount/100 %>
    <%= price.recurring&.interval %>
    <%= price.type %>
    <%= button_to 'Subscribe (full page)', stripe_checkout_path(price_id: price.id), data: {turbo: 'false'} %>
    <%= link_to 'Subscribe (embedded)', stripe_checkout_new_path(price_id: price.id) %>
  </div>
<% end %>